general {
    hide_cursor = false
    grace = 2
    no_fade_in = false
}

background {
    monitor =
    path = ~/Pictures/wallpapers/catppuccin-mocha.png
    blur_passes = 2
    blur_size = 4
    color = rgb(30, 30, 46)
}

input-field {
    monitor =
    size = 260, 55
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    outer_color = rgb(203, 166, 247)
    inner_color = rgb(30, 30, 46)
    font_color = rgb(205, 214, 244)
    fade_on_empty = true
    placeholder_text = <span foreground="##a6adc8">Password...</span>
    position = 0, -60
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = rgba(205, 214, 244, 1)
    font_size = 90
    font_family = JetBrainsMono Nerd Font
    position = 0, 160
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%A, %B %d')"
    color = rgba(186, 194, 222, 1)
    font_size = 22
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}
